# Generated by Django 2.2 on 2019-05-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_page_coutner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='coutner',
            new_name='counter',
        ),
    ]
